/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora.vista;

/**
 *
 * @author JOHN FORERO
 */
public class ventanaCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form ventanaCalculadora
     */
    public ventanaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelHeader = new javax.swing.JPanel();
        lblTituloPrincipal = new javax.swing.JLabel();
        panelPantalla = new javax.swing.JPanel();
        entradaDatoPantalla = new javax.swing.JTextField();
        panelBotones = new javax.swing.JPanel();
        panelBotonesNumeros = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        panelBotonesOperadoresBasicos = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        panelResultado = new javax.swing.JPanel();
        lblTituloResultado = new javax.swing.JLabel();
        salidaDatoSolucion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        panelHeader.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        panelHeader.setMaximumSize(new java.awt.Dimension(32767, 50));
        panelHeader.setMinimumSize(new java.awt.Dimension(166, 50));
        panelHeader.setPreferredSize(new java.awt.Dimension(0, 50));
        panelHeader.setLayout(new java.awt.GridBagLayout());

        lblTituloPrincipal.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        lblTituloPrincipal.setText("Calculadora Basica");
        panelHeader.add(lblTituloPrincipal, new java.awt.GridBagConstraints());

        getContentPane().add(panelHeader);

        panelPantalla.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        panelPantalla.setMaximumSize(new java.awt.Dimension(32767, 70));
        panelPantalla.setPreferredSize(new java.awt.Dimension(0, 70));
        panelPantalla.setLayout(new java.awt.BorderLayout());

        entradaDatoPantalla.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        entradaDatoPantalla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        entradaDatoPantalla.setText("0");
        entradaDatoPantalla.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8)));
        entradaDatoPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaDatoPantallaActionPerformed(evt);
            }
        });
        panelPantalla.add(entradaDatoPantalla, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelPantalla);
        panelPantalla.getAccessibleContext().setAccessibleDescription("");

        panelBotones.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelBotones.setPreferredSize(new java.awt.Dimension(0, 0));
        panelBotones.setLayout(new java.awt.GridBagLayout());

        panelBotonesNumeros.setPreferredSize(new java.awt.Dimension(0, 0));
        panelBotonesNumeros.setRequestFocusEnabled(false);
        panelBotonesNumeros.setLayout(new java.awt.GridLayout(4, 3, 5, 5));

        jButton5.setText("0");
        panelBotonesNumeros.add(jButton5);

        jButton1.setText("0");
        panelBotonesNumeros.add(jButton1);

        jButton2.setText("0");
        panelBotonesNumeros.add(jButton2);

        jButton9.setText("0");
        panelBotonesNumeros.add(jButton9);

        jButton10.setText("0");
        panelBotonesNumeros.add(jButton10);

        jButton11.setText("0");
        panelBotonesNumeros.add(jButton11);

        jButton6.setText("0");
        panelBotonesNumeros.add(jButton6);

        jButton8.setText("0");
        panelBotonesNumeros.add(jButton8);

        jButton22.setText("0");
        panelBotonesNumeros.add(jButton22);

        jButton7.setText("0");
        panelBotonesNumeros.add(jButton7);

        jButton24.setText("0");
        panelBotonesNumeros.add(jButton24);

        jButton23.setText("0");
        panelBotonesNumeros.add(jButton23);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        panelBotones.add(panelBotonesNumeros, gridBagConstraints);

        panelBotonesOperadoresBasicos.setPreferredSize(new java.awt.Dimension(0, 0));
        panelBotonesOperadoresBasicos.setLayout(new java.awt.GridLayout(4, 1, 5, 5));

        jButton13.setText("0");
        panelBotonesOperadoresBasicos.add(jButton13);

        jButton17.setText("0");
        panelBotonesOperadoresBasicos.add(jButton17);

        jButton16.setText("0");
        panelBotonesOperadoresBasicos.add(jButton16);

        jButton27.setText("0");
        panelBotonesOperadoresBasicos.add(jButton27);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelBotones.add(panelBotonesOperadoresBasicos, gridBagConstraints);

        getContentPane().add(panelBotones);

        panelResultado.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10)));
        panelResultado.setMaximumSize(new java.awt.Dimension(32767, 60));
        panelResultado.setMinimumSize(new java.awt.Dimension(132, 60));
        panelResultado.setPreferredSize(new java.awt.Dimension(0, 60));
        panelResultado.setLayout(new javax.swing.BoxLayout(panelResultado, javax.swing.BoxLayout.X_AXIS));

        lblTituloResultado.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblTituloResultado.setText("Resultado :");
        lblTituloResultado.setToolTipText("");
        lblTituloResultado.setMaximumSize(new java.awt.Dimension(100, 54));
        lblTituloResultado.setMinimumSize(new java.awt.Dimension(100, 54));
        lblTituloResultado.setPreferredSize(new java.awt.Dimension(100, 54));
        panelResultado.add(lblTituloResultado);

        salidaDatoSolucion.setEditable(false);
        salidaDatoSolucion.setBackground(new java.awt.Color(252, 252, 252));
        salidaDatoSolucion.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        salidaDatoSolucion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        salidaDatoSolucion.setText("0");
        salidaDatoSolucion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        salidaDatoSolucion.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        salidaDatoSolucion.setMinimumSize(new java.awt.Dimension(12, 40));
        salidaDatoSolucion.setPreferredSize(new java.awt.Dimension(34, 40));
        salidaDatoSolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salidaDatoSolucionActionPerformed(evt);
            }
        });
        panelResultado.add(salidaDatoSolucion);

        getContentPane().add(panelResultado);

        setSize(new java.awt.Dimension(412, 541));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void entradaDatoPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaDatoPantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaDatoPantallaActionPerformed

    private void salidaDatoSolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salidaDatoSolucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salidaDatoSolucionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField entradaDatoPantalla;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel lblTituloPrincipal;
    private javax.swing.JLabel lblTituloResultado;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelBotonesNumeros;
    private javax.swing.JPanel panelBotonesOperadoresBasicos;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelPantalla;
    private javax.swing.JPanel panelResultado;
    private javax.swing.JTextField salidaDatoSolucion;
    // End of variables declaration//GEN-END:variables
}
