/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora.vista;

/**
 *
 * @author JOHN FORERO
 */
public class ventanaCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form ventanaCalculadora
     */
    public ventanaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        panelPantalla = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        panelBotones = new javax.swing.JPanel();
        panelResultado = new javax.swing.JPanel();
        tituloResultado = new javax.swing.JLabel();
        jTextField_resultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        panelHeader.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        panelHeader.setMaximumSize(new java.awt.Dimension(32767, 50));
        panelHeader.setMinimumSize(new java.awt.Dimension(166, 50));
        panelHeader.setPreferredSize(new java.awt.Dimension(0, 50));
        panelHeader.setLayout(new java.awt.GridBagLayout());

        titulo.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        titulo.setText("Calculadora Basica");
        panelHeader.add(titulo, new java.awt.GridBagConstraints());

        getContentPane().add(panelHeader);

        panelPantalla.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        panelPantalla.setMaximumSize(new java.awt.Dimension(32767, 70));
        panelPantalla.setPreferredSize(new java.awt.Dimension(0, 70));
        panelPantalla.setLayout(new java.awt.BorderLayout());

        jTextField1.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("0");
        jTextField1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        panelPantalla.add(jTextField1, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelPantalla);
        panelPantalla.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );

        getContentPane().add(panelBotones);

        panelResultado.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10)));
        panelResultado.setMaximumSize(new java.awt.Dimension(32767, 60));
        panelResultado.setMinimumSize(new java.awt.Dimension(132, 60));
        panelResultado.setPreferredSize(new java.awt.Dimension(0, 60));
        panelResultado.setLayout(new javax.swing.BoxLayout(panelResultado, javax.swing.BoxLayout.X_AXIS));

        tituloResultado.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        tituloResultado.setText("Resultado :");
        tituloResultado.setToolTipText("");
        tituloResultado.setMaximumSize(new java.awt.Dimension(100, 54));
        tituloResultado.setMinimumSize(new java.awt.Dimension(100, 54));
        tituloResultado.setPreferredSize(new java.awt.Dimension(100, 54));
        panelResultado.add(tituloResultado);

        jTextField_resultado.setEditable(false);
        jTextField_resultado.setBackground(new java.awt.Color(252, 252, 252));
        jTextField_resultado.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jTextField_resultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_resultado.setText("0");
        jTextField_resultado.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jTextField_resultado.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        jTextField_resultado.setMinimumSize(new java.awt.Dimension(12, 40));
        jTextField_resultado.setPreferredSize(new java.awt.Dimension(34, 40));
        jTextField_resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_resultadoActionPerformed(evt);
            }
        });
        panelResultado.add(jTextField_resultado);

        getContentPane().add(panelResultado);

        setSize(new java.awt.Dimension(412, 541));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField_resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_resultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_resultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField_resultado;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelPantalla;
    private javax.swing.JPanel panelResultado;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel tituloResultado;
    // End of variables declaration//GEN-END:variables
}
